name: interrupt
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  accordion: ^2.5.1
  circular_countdown_timer: ^0.2.3
  clipboard: ^0.1.3
  cloud_firestore: ^4.4.2
  cupertino_icons: ^1.0.2
  file_picker: ^5.2.5
  firebase_auth: ^4.2.8
  firebase_core: ^2.6.1
  firebase_storage: ^11.0.14
  flowder: ^0.2.0
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: ^0.11.0
  flutter_screenutil: ^5.8.4
  flutter_svg: ^2.0.1
  fluttertoast: ^8.2.2
  font_awesome_flutter: ^10.4.0
  gallery_saver: ^2.3.2
  google_fonts: ^4.0.3
  google_sign_in: ^6.0.0
  http: ^0.13.5
  image_picker: ^0.8.3
  logger: ^1.2.2
  lottie: ^2.2.0
  onboarding: ^3.1.0
  path_provider: ^2.0.13
  pdf_render: ^1.3.7
  percent_indicator: ^4.0.1
  permission_handler: null
  provider: ^6.0.5
  qr_flutter: ^4.0.0
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  intl: ^0.17.0-nullsafety.2
  test_api: 0.5.1

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - .env
